name: leaforgapp
description: leaforgapp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0
code: 7

environment:
  sdk: '>=2.2.2 <3.0.0'
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  global_configuration: ^0.1.2
  http: ^0.13.3
  google_maps_flutter: ^2.0.6
  carousel_slider: ^4.0.0
  mvc_pattern: ^7.2.0
  cached_network_image: ^3.1.0
  fluttertoast: ^8.0.7
  flutter_staggered_grid_view: ^0.4.0
  html: ^0.15.0
  shared_preferences: ^2.0.6
  flutter_html: ^2.1.0
  flutter_svg: ^0.22.0
  location: ^4.3.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.4
  avatar_view: ^1.0.0+3
  map_pin_picker: ^0.0.1
  geolocator: ^7.2.0+1
  intl_phone_number_input: ^0.7.0+2
  flutter_phosphor_icons: ^0.0.1+4
  dropdown_search: ^0.6.1
  provider: ^5.0.0
  google_maps: ^5.1.0
  adv_fab: ^1.0.5
  smooth_scroll_web: ^0.0.4
  ud_design: ^0.0.9
  lazy_loading_list: ^1.0.1
  nine_grid_view: ^2.0.0
  get: ^4.1.4
  firebase_core: ^1.3.0
  firebase_auth: ^3.0.1
  pinput: ^1.2.0
  sms_autofill: ^2.0.0
  intl: ^0.17.0
  uuid: any
  firebase: ^9.0.1
  image_picker: any
  image_cropper: ^1.3.1
  flutter_image_compress: ^1.0.0
  photo_view: ^0.12.0
  cloud_firestore: any
  firebase_storage: any
  firebase_messaging: any
  flutter_local_notifications: any  
  emoji_chooser: ^0.9.2
  fancy_bottom_navigation: ^0.3.3
  story_designer: any
  story: ^0.5.1
  mime: ^1.0.0
  video_compress: ^3.1.0
  keyboard_actions: ^3.3.0+1
  connectivity: ^3.0.6
  path_provider: ^2.0.2
  image: ^3.0.2
  image_picker_web: ^2.0.3+1


  
  flutter_web_plugins:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/
    - assets/images/
    - assets/images/main/
    - assets/images/shops/
    - assets/images/restaurants/
    - assets/images/helpers/
    - assets/images/community/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Poppins-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true